check for mips targets for stat.st_dev definitions
st_dev has wrong type in glibc when using mips/O32 ABI
its type should be dev_t but it is set to unsigned long int
this is specific issue on mips/o32 ABI in glibc for details

See
https://sourceware.org/bugzilla/show_bug.cgi?id=17786

currently the build fails on mips archirecture with type mismatches

      Fixes
      error[E0308]: mismatched types
*        --> /usr/src/debug/python3-pyruvate/1.1.2-r0/cargo_home/bitbake/libsystemd-0.4.1/src/logging.rs:296:25
          |
      296 |                 device: stat.st_dev,
          |                         ^^^^^^^^^^^ expected `u64`, found `u32`

Signed-off-by: Khem Raj <raj.khem@gmail.com>